server:
  port: 9767

spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/imtiazjava/commonconfig-server
          clone-on-start: true